# Generated by Django 5.2.4 on 2025-07-23 11:07

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DanceClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_password', models.CharField(blank=True, max_length=128, null=True)),
                ('club_name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('representative_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choreographers', to='core.danceclub')),
            ],
        ),
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_categories', to='core.event')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Trio', 'Trio'), ('Group', 'Group (4-9)'), ('Formation', 'Formation (10-29)'), ('Production', 'Production (30+)')], max_length=20)),
                ('age_group', models.CharField(choices=[('Mini', 'Mini'), ('Junior', 'Junior'), ('Teen', 'Teen'), ('Senior', 'Senior'), ('Adult', 'Adult')], max_length=20)),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.choreographer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stylecategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Trio', 'Trio'), ('Group', 'Group (4-9)'), ('Formation', 'Formation (10-29)'), ('Production', 'Production (30+)')], max_length=50)),
                ('age_group', models.CharField(choices=[('Mini', 'Mini'), ('Junior', 'Junior'), ('Teen', 'Teen'), ('Senior', 'Senior'), ('Adult', 'Adult')], max_length=50)),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.choreographer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('style_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stylecategory')),
            ],
        ),
    ]
