# Generated by Django 5.2.4 on 2025-07-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='choreographer',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='choreographer',
        ),
        migrations.AddField(
            model_name='participation',
            name='dancer_name',
            field=models.CharField(default='Mihailo', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='core.danceclub')),
            ],
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dancer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dancer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='dancer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dancer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choreographer',
        ),
    ]
