# Generated by Django 5.2.4 on 2025-07-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_eventregistration_choreographer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='dancer_name',
            new_name='choreographer_name',
        ),
    ]
