# Generated by Django 5.2.4 on 2025-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_dancer_name_participation_choreographer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='difficulty',
            field=models.CharField(choices=[('A', 'Advanced'), ('B', 'Beginner/Basic')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
