# Generated by Django 5.2.4 on 2025-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_participation_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='age_group',
            field=models.CharField(choices=[('Baby', 'Baby (5-6)'), ('Mini Kids', 'Mini Kids (7-8)'), ('Kids', 'Kids (9-11)'), ('Teen', 'Teen (12-14)'), ('Youth', 'Youth (15-17)'), ('Adult', 'Adult (18 and up)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participation',
            name='age_group',
            field=models.CharField(choices=[('Baby', 'Baby (5-6)'), ('Mini Kids', 'Mini Kids (7-8)'), ('Kids', 'Kids (9-11)'), ('Teen', 'Teen (12-14)'), ('Youth', 'Youth (15-17)'), ('Adult', 'Adult (18 and up)')], max_length=20),
        ),
    ]
