# Generated by Django 5.2.4 on 2025-07-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_eventregistration_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DancerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancer')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_links', to='core.participation')),
            ],
        ),
    ]
