# Generated by Django 5.2.4 on 2025-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dancerparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
