# Generated by Django 5.2.4 on 2025-07-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participation_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='dancer',
        ),
    ]
