# Generated by Django 5.2.4 on 2025-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_participation_dancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='choreography_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
