# Generated by Django 5.2.4 on 2025-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
