# Generated by Django 5.2.4 on 2025-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_participation_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='group_display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
