# Generated by Django 5.2.4 on 2025-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_participation_group_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music_uploads/'),
        ),
    ]
