# Generated by Django 5.2.4 on 2025-08-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_participation_music_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlaybackState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_highlight_key', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
