# Generated by Django 5.2.4 on 2025-08-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventplaybackstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclub',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
