# Generated by Django 5.2.4 on 2025-08-07 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_danceclub_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creativity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('synchronization', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participation')),
            ],
            options={
                'unique_together': {('participation', 'judge')},
            },
        ),
    ]
