# Generated by Django 5.2.4 on 2025-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgescore',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='judgescore',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='judgescore',
            name='synchronization',
        ),
        migrations.RemoveField(
            model_name='judgescore',
            name='technicality',
        ),
        migrations.AddField(
            model_name='judgescore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final score between 1.00 and 10.00 (step 0.25)', max_digits=4, null=True),
        ),
    ]
