# Generated by Django 5.2.4 on 2025-08-23 09:06

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_judgescore_creativity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danceclub',
            options={'verbose_name': 'Dance Club', 'verbose_name_plural': 'Dance Clubs'},
        ),
        migrations.AlterModelOptions(
            name='dancer',
            options={'verbose_name': 'Dancer', 'verbose_name_plural': 'Dancers'},
        ),
        migrations.AlterModelOptions(
            name='dancerparticipation',
            options={'verbose_name': 'Dancer Participation', 'verbose_name_plural': 'Dancer Participations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventplaybackstate',
            options={'verbose_name': 'Event Playback State', 'verbose_name_plural': 'Event Playback States'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterModelOptions(
            name='judgescore',
            options={'verbose_name': 'Judge Score', 'verbose_name_plural': 'Judge Scores'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
        migrations.AlterModelOptions(
            name='stylecategory',
            options={'verbose_name': 'Style Category', 'verbose_name_plural': 'Style Categories'},
        ),
        migrations.RemoveField(
            model_name='judgescore',
            name='score',
        ),
        migrations.AddField(
            model_name='judgescore',
            name='composition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='judgescore',
            name='image',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='judgescore',
            name='show_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='judgescore',
            name='technique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='club_name',
            field=models.CharField(max_length=255, verbose_name='Club Name'),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Raw Password'),
        ),
        migrations.AlterField(
            model_name='danceclub',
            name='representative_name',
            field=models.CharField(max_length=255, verbose_name='Representative Name'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='core.danceclub', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='dancerparticipation',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancer', verbose_name='Dancer'),
        ),
        migrations.AlterField(
            model_name='dancerparticipation',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_links', to='core.participation', verbose_name='Participation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='results_published',
            field=models.BooleanField(default=False, verbose_name='Results Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='eventplaybackstate',
            name='current_highlight_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Highlight Key'),
        ),
        migrations.AlterField(
            model_name='eventplaybackstate',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='age_group',
            field=models.CharField(choices=[('Baby', 'Baby (5-6)'), ('Mini Kids', 'Mini Kids (7-8)'), ('Kids', 'Kids (9-11)'), ('Teen', 'Teen (12-14)'), ('Youth', 'Youth (15-17)'), ('Adult', 'Adult (18 and up)')], max_length=50, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancer', verbose_name='Dancer'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='group_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Trio', 'Trio'), ('Group', 'Group (4-9)'), ('Formation', 'Formation (10-29)'), ('Production', 'Production (30+)')], max_length=50, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='style_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stylecategory', verbose_name='Style Category'),
        ),
        migrations.AlterField(
            model_name='judgescore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Judge'),
        ),
        migrations.AlterField(
            model_name='judgescore',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participation', verbose_name='Participation'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='age_group',
            field=models.CharField(choices=[('Baby', 'Baby (5-6)'), ('Mini Kids', 'Mini Kids (7-8)'), ('Kids', 'Kids (9-11)'), ('Teen', 'Teen (12-14)'), ('Youth', 'Youth (15-17)'), ('Adult', 'Adult (18 and up)')], max_length=20, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='choreographer_name',
            field=models.CharField(max_length=255, verbose_name='Choreographer Name'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='choreography_name',
            field=models.CharField(default='Untitled', max_length=255, verbose_name='Choreography Name'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='difficulty',
            field=models.CharField(choices=[('A', 'Advanced'), ('B', 'Beginner/Basic')], max_length=1, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='group_display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Group Display Order'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='group_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Trio', 'Trio'), ('Group', 'Group (4-9)'), ('Formation', 'Formation (10-29)'), ('Production', 'Production (30+)')], max_length=20, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music_uploads/', verbose_name='Music File'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stylecategory', verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_categories', to='core.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='danceclub',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_club_user'),
        ),
    ]
