# Generated by Django 5.2.4 on 2025-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_danceclub_options_alter_dancer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notice_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
