# Generated by Django 5.2.4 on 2025-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_event_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notice_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/', verbose_name='Event Poster / Notice'),
        ),
    ]
