# Generated by Django 5.2.4 on 2025-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_event_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_registrations',
            field=models.BooleanField(default=False),
        ),
    ]
