# Generated by Django 5.2.4 on 2025-08-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_event_allow_registrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
