# Generated by Django 5.2.4 on 2025-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_danceclub_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_list_published',
            field=models.BooleanField(default=False, verbose_name='Is Start List Published'),
        ),
    ]
