# Generated by Django 5.2.4 on 2025-09-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event_start_list_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('placement', models.PositiveIntegerField(verbose_name='Placement')),
                ('image', models.ImageField(upload_to='diplomas/', verbose_name='Diploma Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancer', verbose_name='Dancer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
            },
        ),
    ]
