# Generated by Django 5.2.4 on 2025-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='diploma_template',
            field=models.ImageField(blank=True, null=True, upload_to='diploma_templates/', verbose_name='Diploma Template'),
        ),
    ]
