# Generated by Django 5.2.4 on 2025-09-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_event_diploma_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceclub',
            name='raw_password',
        ),
    ]
