# Generated by Django 5.2.4 on 2025-09-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_startlistslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startlistslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='startlistslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='startlistslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Duration (minutes)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startlistslot',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
    ]
