# Generated by Django 5.2.4 on 2025-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_startlistslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlistslot',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Baby', 'Baby (5-6)'), ('Mini Kids', 'Mini Kids (7-8)'), ('Kids', 'Kids (9-11)'), ('Teen', 'Teen (12-14)'), ('Youth', 'Youth (15-17)'), ('Adult', 'Adult (18 and up)')], max_length=20, null=True, verbose_name='Age Group (optional)'),
        ),
    ]
