# Generated by Django 5.2.4 on 2025-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_startlistslot_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlistslot',
            name='is_ceremony',
            field=models.BooleanField(default=False),
        ),
    ]
