# Generated by Django 5.2.4 on 2025-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_startlistslot_is_ceremony'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='music_end',
            field=models.DateField(blank=True, null=True, verbose_name='Music Upload End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateField(blank=True, null=True, verbose_name='Registration End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Start Date'),
        ),
    ]
